import "@/app/globals.css";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    default: "Ecommerce | Renaldis",
    template: "%s | Renaldis",
  },
  description: "Generated by Next.JS",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
